on:
  push:
    branches:
      - develop
name: Dev Deploy
jobs:
  deploy_job:
    name: Dev Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: deploy file
      uses: stifdrp/SFTP-Docker-Deploy-Action@master
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USER }}
        sysusername: ${{ secrets.SFTP_SYSUSER }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_path: ${{ secrets.REMOTE_PATH_DEV }}
        port: ${{ secrets.SFTP_PORT }}
        args: '-o ConnectTimeout=5'
